idtitlecreatedAtclosedAtclosed
MDU6SXNzdWUxOTMyNjEzMDg=osx - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte2016-12-03T03:02:30Z2016-12-03T03:25:05ZTrue
MDU6SXNzdWUxOTMyNjIzNjk=neuralconvo.ini + missing data/train.enc2016-12-03T03:27:12Z2017-05-10T16:17:04ZTrue
MDU6SXNzdWUxOTMyNjI5MjE=fyi- this is how you want to do a tensorflow chat bot project2016-12-03T03:39:23Z2017-05-10T15:20:20ZTrue
MDU6SXNzdWUxOTMyNjY5NDM=Error while running execute.py2016-12-03T05:24:16ZFalse
MDU6SXNzdWUxOTMzNjkzMTk=UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte2016-12-04T19:23:28ZFalse
MDU6SXNzdWUxOTM1MTY5MTg=Python newb stuck launching execute2016-12-05T14:47:19Z2016-12-05T19:44:28ZTrue
MDU6SXNzdWUxOTM1NjY4Nzk=Can't get a good enough perplexity score2016-12-05T17:55:41Z2016-12-15T20:48:11ZTrue
MDU6SXNzdWUxOTM3NjEyOTQ=size _UNK _UNK2016-12-06T12:34:32Z2016-12-09T07:18:47ZTrue
MDU6SXNzdWUxOTM5MjgzMjg=AttributeError: module 'execute' has no attribute 'init_session'2016-12-07T00:49:52ZFalse
MDU6SXNzdWUxOTQyNTE3MjA=Not Restoring Checkpoints2016-12-08T05:39:50Z2016-12-08T06:37:35ZTrue
MDU6SXNzdWUxOTQ2NDA5MDM=NotFoundError: data/test.enc2016-12-09T16:39:48Z2016-12-09T19:11:11ZTrue
MDU6SXNzdWUxOTU2ODc0ODg="After 23000 step, when I input something but  I only get the ""size _UNK """2016-12-15T00:50:08ZFalse
MDU6SXNzdWUxOTYzMDE0MzY=No reference to data/test.dec in seq2seq.ini?2016-12-18T21:47:27ZFalse
MDU6SXNzdWUxOTY4NTUxMzE=(non-issue)could this chat bot used in chinese language?2016-12-21T06:17:10Z2016-12-27T01:52:28ZTrue
MDU6SXNzdWUxOTc0ODQwOTU=UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position N: invalid start byte2016-12-25T01:54:09ZFalse
MDU6SXNzdWUxOTc2MDY1NDE=Bucket perplexity increasing : why ?2016-12-26T17:22:57Z2016-12-29T12:01:43ZTrue
MDU6SXNzdWUxOTgwNjYzMjA=After 509700 steps, am still getting bad results using TF 0.12 and training on gtx10702016-12-29T20:47:09ZFalse
MDU6SXNzdWUxOTg2NTYyMDc="After long time training ,when I run with ""test"", but get Error ""IndexError: list index out of range"""2017-01-04T08:45:45ZFalse
MDU6SXNzdWUxOTkzODU1NjY=lear2017-01-07T21:14:52ZFalse
MDU6SXNzdWUxOTk0NjQ5MTQ=hey guys, I had fixed some bugs in the code. Now can run in python32017-01-09T01:59:05ZFalse
MDU6SXNzdWUxOTk3MDgzODI=how to test the chatbot2017-01-10T01:20:19Z2017-01-10T01:23:21ZTrue
MDU6SXNzdWUyMDg2MTkwMDk=Breaks in latest TensorFlow 1.0.02017-02-18T06:34:09Z2017-02-21T05:56:18ZTrue
MDU6SXNzdWUyMDg2MjExMjQ=How long does it normally take to train the sample data2017-02-18T07:12:45Z2017-02-21T22:20:33ZTrue
MDU6SXNzdWUyMDg4ODIyNzg=No module named models.rnn.translate2017-02-20T13:38:54ZFalse
MDU6SXNzdWUyMDkwMzE2Mzk=ImportError: No module named 'tensorflow.models'2017-02-21T03:17:36Z2017-02-21T13:00:42ZTrue
MDU6SXNzdWUyMDk3ODUyOTI=Issues after changing all the imports for TF 1.0.02017-02-23T14:59:04ZFalse
MDU6SXNzdWUyMTIyMDEwNjY=after training for days on GPU...2017-03-06T17:57:37ZFalse
MDU6SXNzdWUyMTI4MjY2Nzc=getting segmentation fault while running execute.py file2017-03-08T19:07:11Z2017-03-08T21:38:59ZTrue
MDU6SXNzdWUyMTM1ODEyNTg=not able to restart training from a checkpoint.2017-03-12T04:34:39Z2017-03-12T05:46:34ZTrue
MDU6SXNzdWUyMTM1OTk2OTU=Error at reading data line 100000: Received a label value of 19143 which is outside the valid range of [0, 256).2017-03-12T11:53:35Z2019-07-06T03:04:51ZTrue
MDU6SXNzdWUyMTUwNjQ0MzU=Incomplete documentation on the training data2017-03-17T17:01:53ZFalse
MDU6SXNzdWUyMjQyNjg0MDA=ValueError: Attempt to reuse RNNCell2017-04-25T20:51:57Z2017-05-05T20:18:09ZTrue
MDU6SXNzdWUyMjU0MzAyMTY=Where is the dataset to be loaded ?2017-05-01T12:54:05ZFalse
MDU6SXNzdWUyMjU5NzgxMjM=How to update dataset every day and  train chatbot on updated dataset.2017-05-03T13:01:39ZFalse
MDU6SXNzdWUyMjY4MTQyNTQ=Unsuccessful TensorSliceReader constructor2017-05-07T00:03:39ZFalse
MDU6SXNzdWUyMjgyMzQ5NDI=Whatever you say is going back to _UNK2017-05-12T09:21:12ZFalse
MDU6SXNzdWUyMjg0NTk1NTE=issues new version tensorflow2017-05-13T08:52:27ZFalse
MDU6SXNzdWUyMjk1ODA3NTI=A small problem2017-05-18T07:36:40Z2017-05-31T01:35:17ZTrue
MDU6SXNzdWUyMzAyMDA0NDk=TypeError: can't pickle _thread.lock objects2017-05-21T06:26:04Z2017-05-22T05:40:01ZTrue
MDU6SXNzdWUyMzAzMDg5MTM=ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.GRUCell object at 0x7f8317334a90> with a different variable scope than its first use. 2017-05-22T07:37:31Z2017-09-26T04:50:37ZTrue
MDU6SXNzdWUyMzEyNDY5NTk=Typo seq2seq_serve.ini2017-05-25T05:48:07ZFalse
MDU6SXNzdWUyMzQyMTY3OTQ=What are some good 'questions' to ask the ChatBot as it's training?2017-06-07T13:52:08ZFalse
MDU6SXNzdWUyMzY0ODUxMTQ=Does anyone know if this works with tensorflow 1.2.0?2017-06-16T13:36:23ZFalse
MDU6SXNzdWUyMzc0MzAwNzc=Error executing python execute.py after installing the dependencies (i had installed tensorflow in virtualenv)2017-06-21T06:42:45ZFalse
MDU6SXNzdWUyMzkxMTc5MTk=Useless output at 42500 steps2017-06-28T10:19:11ZFalse
MDU6SXNzdWUyNDQ0NzM4NzM=Can't import data_utils(no module named tensorflow.models)2017-07-20T19:36:20ZFalse
MDU6SXNzdWUyNDY1ODk3Njk='module' object has no attribute 'seq2seq'2017-07-30T15:14:26ZFalse
MDU6SXNzdWUyNDY2MzU4NTI=Gibberish2017-07-31T03:29:40ZFalse
MDU6SXNzdWUyNDcwNTE1MjY=Missing train directory?2017-08-01T12:25:19ZFalse
MDU6SXNzdWUyNDgyNzEwMDU=.2017-08-06T20:45:35ZFalse
MDU6SXNzdWUyNDk1NTM0ODE=Mac OSX Sierra missing imports2017-08-11T07:03:22ZFalse
MDU6SXNzdWUyNTQ2NzAwMTE=I meet a problem when I change the mode = test. Can anybody help me please 2017-09-01T15:09:10ZFalse
MDU6SXNzdWUyNTUxMzg4ODA='module' object has no attribute 'seq2seq'2017-09-05T01:42:17ZFalse
MDU6SXNzdWUyNTU2OTU0ODM=.2017-09-06T18:12:37ZFalse
MDU6SXNzdWUyNTYzMzcxMTM=While training the seq2seq the program gets killed i am using CPU only tensorflow2017-09-08T18:35:25ZFalse
MDU6SXNzdWUyNTgzNzAxNzY="When I set the seq to serve mode and run the ui/app.py I get a Traceback (most recent call last):   File ""ui/app.py"", line 29, in <module>     sess, model, enc_vocab, rev_dec_vocab = execute.init_session(sess, conf='seq2seq_serve.ini') AttributeError: 'module' object has no attribute 'init_session'"2017-09-18T04:53:44ZFalse
MDU6SXNzdWUyNjI0Nzk5NDE=Issues in training the model on macOS Sierra2017-10-03T15:45:28ZFalse
MDU6SXNzdWUyNjUyOTIzMDc=Error on Ubuntu in VMware2017-10-13T13:38:42ZFalse
MDU6SXNzdWUyNjYxNjQ0OTU=IndexError: list index out of range when testing the Chatbot2017-10-17T15:11:12ZFalse
MDU6SXNzdWUyNjk4NDkxMzc=TypeError: write() argument 1 must be unicode, not str2017-10-31T06:28:48ZFalse
MDU6SXNzdWUyNzI0Mjc4OTA=Get this error how to solve it.2017-11-09T03:22:18ZFalse
MDU6SXNzdWUyNzQzOTUxMTk=So this happened when I tried to run execute.py2017-11-16T04:59:00ZFalse
MDU6SXNzdWUyNzUxNzY4MjU=Error when running execute.py - missing directory data? 2017-11-19T17:36:18Z2017-11-19T17:39:44ZTrue
MDU6SXNzdWUyNzk3ODkwMzU=Update Code to work on Latest Tensorflow2017-12-06T15:13:53ZFalse
MDU6SXNzdWUyODI4MzU5OTU=what is the output2017-12-18T10:47:45ZFalse
MDU6SXNzdWUyODM4NzcwOTY=Can I train mysql database tables using this?2017-12-21T13:08:40ZFalse
MDU6SXNzdWUyODc0NTgyMTY=Issue with execute.py2018-01-10T14:45:39ZFalse
MDU6SXNzdWUyODgwMDgxNzc=TypeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'2018-01-12T04:58:57ZFalse
MDU6SXNzdWUyODg3ODE2Mzg=i don't know what's mean Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX22018-01-16T04:19:37ZFalse
MDU6SXNzdWUyOTY2OTY2NTg=Cannot test after training!2018-02-13T11:02:37ZFalse
MDU6SXNzdWUzMDQwNDg0NjI= Got ConfigParser.NoSectionError: No section: 'ints'2018-03-10T06:59:43ZFalse
MDU6SXNzdWUzMDg1NTY2OTY=InvalidArgumentError: indices[40] = 2000 0 is not in [0, 20000)2018-03-26T12:45:42ZFalse
MDU6SXNzdWUzMjY5NjAzNzA=Tensorflow Variable scope issue2018-05-28T09:28:01ZFalse
MDU6SXNzdWUzMjk2OTU0MjM=Error messages, please help2018-06-06T03:13:57ZFalse
MDU6SXNzdWUzMzQzNTkwNTk=ValueError: Decoder length must be equal to the one in bucket, 1 != 25.2018-06-21T06:45:05ZFalse
MDU6SXNzdWUzMzY2NDE0NTY=No source found error while try to run execute.py.I do have vocab decoder and encoder data in working dir2018-06-28T14:18:05ZFalse
MDU6SXNzdWUzNTY0MjgzNDM=how to train my own data2018-09-03T09:35:14ZFalse
MDU6SXNzdWUzNTY0MzEyMDE=Cornell Movie Dialog Dataset2018-09-03T09:43:24ZFalse
MDU6SXNzdWUzNjA1OTkyODM=Issue with Global Step Iteration2018-09-16T03:46:59ZFalse
MDU6SXNzdWUzNjU5MzAyMTQ=change test decoder path2018-10-02T14:39:37ZFalse
MDU6SXNzdWUzNzM0Nzc2ODQ=ERROR IN 2018-10-24T13:16:40ZFalse
MDU6SXNzdWUzODU1NTQxMDg=GPUOptions' object has no attribute 'allocator_type'2018-11-29T03:28:23ZFalse
MDU6SXNzdWUzOTg4MzI0MjI=AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'2019-01-14T10:43:55ZFalse
MDU6SXNzdWU0MTkxNTYyMjE=ERROR : python excute.py2019-03-10T07:32:02ZFalse
MDU6SXNzdWU0Mjk2MjIyNjg=rlanesdoonn2019-04-05T07:37:25Z2019-04-05T07:37:32ZTrue
MDU6SXNzdWU0OTM4MDkzNTM=Py to Exe 2019-09-16T00:59:26ZFalse
MDU6SXNzdWU1NzkzNzI1MTI=migrate to tensorflow 2.10 2020-03-11T15:59:25ZFalse
