idtitlecreatedAtclosedAtclosed
MDU6SXNzdWUzNDM3NDczNDI=Hi man, how i set the .json file for the auth?2018-07-23T18:36:59Z2018-07-23T20:35:06ZTrue
MDU6SXNzdWUzNDQxMTU3MjE=Encryption and chunk file read2018-07-24T16:36:36ZFalse
MDU6SXNzdWUzNDQ3NTE3MjM=Add listing of overall storage saved by UDS2018-07-26T08:50:11Z2018-09-10T11:36:14ZTrue
MDU6SXNzdWUzNDgxMDYyMjU=Increase data stored on documents by changing the encoding / formatting?2018-08-06T22:43:05Z2018-12-04T23:19:21ZTrue
MDU6SXNzdWUzNDg1MzU4MjM=KeyError: '_module'2018-08-08T00:49:36Z2019-02-14T11:30:31ZTrue
MDU6SXNzdWUzODczMjM1Nzk=Invalid Syntax Line 2192018-12-04T14:53:29Z2018-12-04T23:18:49ZTrue
MDU6SXNzdWUzODc1MTIwMTc=Undefined names in Encoder.py2018-12-04T22:40:35Z2018-12-04T23:18:02ZTrue
MDU6SXNzdWUzODc1NjE5ODM=[Deleted]2018-12-05T02:07:57Z2018-12-05T09:06:48ZTrue
MDU6SXNzdWUzODc3MDI3MTA=Add a working folder structure2018-12-05T10:59:41ZFalse
MDU6SXNzdWUzODc4Nzk2MjI=googleapiclient :: missing module2018-12-05T18:07:01ZFalse
MDU6SXNzdWUzODc5ODg5ODY=Using on mac, invalid syntax error, line 2262018-12-05T23:20:15Z2019-03-07T23:54:08ZTrue
MDU6SXNzdWUzODgxMjg3NjI=Multi File Support2018-12-06T09:37:11Z2019-02-27T04:00:40ZTrue
MDU6SXNzdWUzODgxODAwMjI=Missing variables in uds.py2018-12-06T11:52:34Z2018-12-07T01:20:06ZTrue
MDU6SXNzdWUzODg5ODcyNTE=Ignore2018-12-09T04:50:48Z2018-12-20T03:58:47ZTrue
MDU6SXNzdWUzOTU3NjIxNDA=Increase Upload Speed2019-01-03T23:33:09ZFalse
MDU6SXNzdWU0MDYxMTE2ODc=Delete not working?2019-02-03T17:43:27Z2019-02-10T20:12:10ZTrue
MDU6SXNzdWU0MDk3ODQwNjE=Delete shows help list without deleting2019-02-13T12:35:22Z2019-02-13T12:36:03ZTrue
MDU6SXNzdWU0MTA5NzEzMDA=Not a UDS File2019-02-15T22:24:27Z2019-02-15T22:37:15ZTrue
MDU6SXNzdWU0MTIyMjg4ODI=ModuleNotFoundError: No module named 'oauth2client'2019-02-20T03:33:48Z2019-03-07T23:54:18ZTrue
MDU6SXNzdWU0MTY1NjY2ODA=Questions2019-03-03T21:24:12Z2019-03-03T21:43:53ZTrue
MDU6SXNzdWU0MTg0NDEyNjg=Uploading Folders2019-03-07T17:59:45ZFalse
MDU6SXNzdWU0MjYyNjg5ODI=error with line 16 (import urllib.request)2019-03-28T02:41:34Z2019-05-17T21:27:59ZTrue
MDU6SXNzdWU0MzI4NDc1NDM=Thoughts2019-04-13T13:27:06Z2019-04-13T15:58:38ZTrue
MDU6SXNzdWU0MzQyNTY0NDg="  File ""uds.py"", line 545, in <module>  "2019-04-17T12:30:38Z2019-05-14T17:42:41ZTrue
MDU6SXNzdWU0NDQyMzU1MTE=Typo in readme file2019-05-15T04:53:02ZFalse
MDU6SXNzdWU0NDQyMzk4OTg=Base852019-05-15T05:13:49Z2019-05-15T05:33:40ZTrue
MDU6SXNzdWU0NDQzMzc2MTE=FUSE integration2019-05-15T09:41:40ZFalse
MDU6SXNzdWU0NDQ1NzMwOTQ=Consider using base85 instead of base64?2019-05-15T18:06:13Z2019-05-15T18:38:54ZTrue
MDU6SXNzdWU0NDQ1ODkxNTg="""Unlimited""?"2019-05-15T18:45:09Z2019-05-15T18:58:23ZTrue
MDU6SXNzdWU0NDQ2MTY4MTk=Mount as a drive?2019-05-15T19:55:02Z2019-05-16T23:41:39ZTrue
MDU6SXNzdWU0NDQ2NzQ2MjU=is it possible to store the uds file inside the google itself?2019-05-15T22:32:36Z2019-06-06T09:19:25ZTrue
MDU6SXNzdWU0NDUyMzcyMDY=Can't run initial setup2019-05-17T02:31:12Z2019-05-17T10:40:09ZTrue
MDU6SXNzdWU0NDUyMzc2NTI=win10 error2019-05-17T02:33:27Z2019-05-17T10:39:30ZTrue
MDU6SXNzdWU0NDU0MzI1ODM=Use Google Photos2019-05-17T13:04:43Z2019-05-17T13:29:24ZTrue
MDU6SXNzdWU0NDU2MDcxNDE=audio2019-05-17T20:32:17Z2019-05-24T17:27:07ZTrue
MDU6SXNzdWU0NDU2MzMyMTE=GUI around the tool2019-05-17T21:59:44Z2019-05-22T11:06:57ZTrue
MDU6SXNzdWU0NDU2NDM5Nzc=Where are the files located in drive?  Storing files in folders?  Sharing files?  Working offline?2019-05-17T22:50:30Z2019-05-19T11:43:09ZTrue
MDU6SXNzdWU0NDU2OTc4MDU=Pull bug?2019-05-18T09:27:57Z2019-05-19T11:32:09ZTrue
MDU6SXNzdWU0NDU4MjM4NDE=Issue running initial setup2019-05-19T14:06:11Z2019-05-19T14:33:50ZTrue
MDU6SXNzdWU0NDYxODI5ODc=tqdm arguments issue2019-05-20T15:34:00Z2019-05-20T15:42:14ZTrue
MDU6SXNzdWU0NDcwNjE4NDM=table of User.txt2019-05-22T10:40:51Z2019-05-22T14:29:39ZTrue
MDU6SXNzdWU0NDg5NjU5ODg=Replace oauth2client with google-auth2019-05-27T18:58:34ZFalse
MDU6SXNzdWU0NTAzNDM5OTU=[BUG]uploaded but no uds found2019-05-30T14:44:56Z2019-05-30T15:26:18ZTrue
MDU6SXNzdWU0NTE0ODk5NDc=Upload from download link2019-06-03T13:40:15ZFalse
MDU6SXNzdWU0NTI4MDUxOTI=[BUG] Google Login?2019-06-06T02:45:26Z2019-06-11T17:06:39ZTrue
MDU6SXNzdWU0NTQ5NzY3NzE=resume from break-point when downloding network problem happend2019-06-12T01:59:22ZFalse
MDU6SXNzdWU0NjQ5NDEwMDg=uds.py -list [BUG]2019-07-07T11:08:29ZFalse
MDU6SXNzdWU0NzA3MzMzOTQ=[BUG] ValueError: mmap length is too long2019-07-21T02:10:25ZFalse
MDU6SXNzdWU0NzI2NDU2Nzg=[BUG] can not push a file2019-07-25T03:25:28ZFalse
MDU6SXNzdWU0OTY3NjY2NjM=Base64 Conversion2019-09-22T11:26:32ZFalse
MDU6SXNzdWU0OTc3ODQzMjk=[BUG]Cannot Login into My Google Account2019-09-24T16:05:48Z2019-09-24T16:51:21ZTrue
MDU6SXNzdWU1MTcxODUxNDk="[BUG] ./uds.py --list crashes with error message; ./uds.py --list ""query"" works"2019-11-04T14:23:20ZFalse
MDU6SXNzdWU1MzgxMzY0ODM= ERROR: Command errored out with exit status 1[BUG]2019-12-16T01:06:01Z2019-12-17T15:35:56ZTrue
MDU6SXNzdWU1MzkzOTUxMzE=Python 3 uds.py shows ERROR!2019-12-18T01:13:05ZFalse
MDU6SXNzdWU1NzM3NjU0ODg=Instantly Closes[BUG]2020-03-02T07:13:48Z2020-03-03T03:05:23ZTrue
MDU6SXNzdWU1Nzc0ODIxOTY=uds.py -list2020-03-08T10:57:44ZFalse
MDU6SXNzdWU1NzgxNTgwOTU=uploading from uploads folder2020-03-09T20:03:55ZFalse
MDU6SXNzdWU2MDU2ODE4NTU=Duplicati bridge2020-04-23T16:38:41ZFalse
MDU6SXNzdWU2MDY5NDE5NDE=KeyError: '_module'2020-04-26T07:16:21ZFalse
